name: CI with Submodules

on:
  push:
    branches:
      - develop2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }} # Necesario si tus submódulos son privados
          submodules: true # Inicializa y actualiza los submódulos

      - name: enter to submodule
        run: cat ./apps/health/README.md
