name: CI with Submodules

on:
  push:
    branches:
      - develop2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   ssh-key: ${{ secrets.SSH_PRIVATE_KEY }} # Necesario si tus submódulos son privados

      - name: clone submodule
        uses: actions/checkout@v4
        with:
          repository: daniv293/sso
          path: apps/sso
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true

      - name: enter to submodule
        run: |
          pwd
          cat ./apps/sso/README.md
